### ISSUE TITLE
[BUG]: showDialog returns a null value but onWillPop expects a bool

### ISSUE THREAD

**Issue by shashvat1965** [CCExtractor/taskwarrior-flutter#99]
Method to Reproduce:
1) Add a tag to a task
2) Go back to the task_details screen
3) Go back without saving and press yes on the dialog box that comes.

Console:
`Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<bool>'
E/flutter (29090): #0      _DetailRouteState.build.<anonymous closure> (package:taskwarrior/services/task_details.dart:150:18)
E/flutter (29090): <asynchronous suspension>
E/flutter (29090): #1      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1492:11)
E/flutter (29090): <asynchronous suspension>
E/flutter (29090): #2      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:4938:45)`

**Comment by shashvat1965** [comment]
#100 should fix the error
